export const Account_EditAccount = {
    breadcrumbsLinkFrontPage: "首頁",
    breadcrumbsLinkMemberCentre:"會員中心",
    breadcrumbsLinkAccountEdit: "帳戶編輯",
    personal: "個人專區",
    account: "帳戶資訊",
    surname: "姓",
    name: "名", 
    changePass: "變更密碼",
    oldPassword: "舊密碼",
    newPassword: "新密碼",
    requiredInput: "必填欄位。請重新輸入。",
    requiredCharacters: "必填欄位；請輸入至少8個字元，並包含至少一個大寫、一個小寫、一个數字和一個特殊字元",
    passwordAgain: "確認新密碼",
    required: "必填欄位。確認密碼需與新密碼相同。",
    saveBtn: "送出",
    accountDelete: "帳號刪除",
    confirmDelete: "您的帳號將被永久刪除，您一旦刪除後，帳號將無法復原，請您務必確定操作。",
    deleteAccount: "刪除帳號",
};