export const Account_Application = {
    breadcrumbsLinkFrontPage: "首页",
    breadcrumbsLinkMemberCentre:"会员中心",
    breadcrumbsLinkAuthManagement: "权限管理",
    customerNormalIndustryAtricles:"行业应用文章",
    customerNormalProductQuery: "产品查询",
    customerNormalNewTechnology: "新技术合作",
    customerNormalOnlineChatRoom: "线上客服聊天室",
    customerEnterpriseProductQuotation: "优选产品报价含零组件、方案与整机",
    customerEnterpriseCustomizedService: "客制化服务专案报价含零组件、方案与整机",
    customerEnterpriseRMAApply: "RMA 申请",
    customerEnterpriseAnalyzeApply: "解析申请",
    customerEnterpriseGreenRegulationApply: "绿色法规申请",
    customerEnterpriseHSDCustomerService: "+ 以及所有HannStar 客戶一般會員的服務",
    partnerNormalNewTechnology: "新技术合作",
    partnerNormalIndustryAtricles: "行业应用文章",
    partnerNormalProductQuery: "产品查询",
    partnerNormalOnlineChatRoom: "线上客服聊天室",
    partnerEnterpriseSupplierPlatform: "供应商资讯交流平台",
    partnerEnterpriseHSDSupplierService: "+ 以及所有HannStar 供应商一般会员的服务",
    contentSubTitle: "权限类别",
    contentRank: "权限说明",
    contentText: "您现在是",
    contentMember: "一般会员",
    contentPendingText: "您目前的状态是",
    contentPendingStates: "申请企业会员 - 审核中",
    contentBecome: "您可以进一步成为",
    contentCompanyMember: "企业会员",
    contentCustomerPermission: "客户权限说明",
    contentApplyMembership: "申请客户企业会员",
    contentApplyPartnership: "申请供应商企业会员",
    contentSupplierLimit: "供应商权限说明",
};