export const Account_Personal = {
    breadcrumbsLinkFrontPage: "首页",
    breadcrumbsLinkMemberCentre:"会员中心",
    breadcrumbsLinkMemberCentrePermissions:"我的权限",
    JobAttributes:{
        title: "工作属性",
        businessRelated:"业务相关",
        purchasing:"采购相关",
        related:"研发相关",
        qualityRelated:"品质相关",
        projectManagement :"项目管理",
        management :"经营管理",
        other:"其他",
    },
    InterestedType:{
        title: "感兴趣的应用别(可复选)",
        smartRetail:"智慧零售",
        wisdomRecreation:"智慧育乐",
        intelligentBuilding:"智能建筑",
        healthCare:"健康关怀",
        transportation:"交通运输",
        smartManufacturing:"智能制造",
    },
    BusinessType: {
        title: "商业类型",
        agent: "代理商",
        dealer: "经销商",
        moduleFactory: "模组厂",
        solutionProvider: "方案商",
        systemIntegrationFactory: "系统整合厂",
        brandFactory: "品牌厂",
        other: "其他",
    },
    CompanyEmpNumber: {
        title: "员工总数",
        option1: "<100",
        option2: "100-500", 
        option3: "500-1000", 
        option4: ">1000", 
      },
      AnnualRevenue: {
        title: "年营业额(USD)",
        option1: "<1M",
        option2: "1M-5M", 
        option3: "5M-10M", 
        option4: "10M-30M",
        option5: ">30M",
      },
      CompanyStockOn: {
        title: "上市公司",
        option1: "是",
        option2: "否",
    },
    CompanyMA1: {
        title: "公司产品主要销售分类(可复选)",
        option1: "车载",
        option2: "穿戴",
        option3: "工控",
        option4: "手机",
        option5: "消费类",
        option6: "其他",
    },
    HannstarYN: {
        title: "是否已使用HannStar产品?",
        option1: "是(请在协助以下资讯)",
        option2: "否/不确定",
      },
      Buy1: {
        title: "购买渠道-1",
        option1: "瀚宇彩晶",
        option2: "代理商",
        option3: "其他",
    },
    Buy2: {
        title: "购买渠道-2",
        option1: "瀚宇彩晶",
        option2: "代理商", 
        option3: "其他",
      },
   Buy3: {
        title: "购买渠道-3",
        option1: "瀚宇彩晶", 
        option2: "代理商", 
        option3: "其他", 
      },
   JobTitle: {
        title: "职称",
        option1: "创办人/董事长", 
        option2: "执行长/总经理/协理", 
        option3: "总监/处长/经理", 
        option4: "主任/课长/组长",
        option5: "专员/管理师",
        option6: "工程师",
        option7: "其他类型",

      },
    CompanyMA2:"公司产品主要销售地区-1",
    CompanyMA3:"公司产品主要销售地区-2",
    CompanyMA4:"公司产品主要销售地区-3",
    TOP1:"主要出货客户-1",
    TOP2:"主要出货客户-2",
    TOP3:"主要出货客户-3",
    BuyCompany1: "渠道公司名称-1",
    BuyCompany2: "渠道公司名称-2",
    BuyCompany3: "渠道公司名称-3",
    CompanyRemark: "备注说明",
    TaxNo: "企业编号(统编/税号)",
    Weblink: "公司网址",
    Country: "地区",
    AreaCity: "城市",
    AreaAddress: "地址",
    CompanyName: "公司名称",
    CompanySName: "公司名称关键字",
    PhoneNumber0: "",
    PhoneNumber1: "电话号码",
    PhoneNumber2: "分机",
    CellPhoneNumber0: "",
    CellPhoneNumber1: "手机号码",
    ApplyMembership: "申请企业会员",
    Step1: "步骤 1. 请选择您的身份",
    Step2: "步骤 2. 申请人资讯",
    Step3: "步骤 3. 企业资料",
    Step4: "为能提供更完整的服务，请问贵司是否已使用HannStar产品?",
    Goback: "回上一页",
    Notes: "备注说明",
    Application: "确认申请",
    Required: "必填栏位。请重新输入。"
};