export const Account_EditAccount = {
    breadcrumbsLinkFrontPage: "首页",
    breadcrumbsLinkMemberCentre:"会员中心",
    breadcrumbsLinkAccountEdit: "帐户编辑",
    personal: "个人专区",
    account: "帐户资讯",
    surname: "姓",
    name: "名", 
    changePass: "变更密码",
    oldPassword: "旧密码",
    newPassword: "新密码",
    requiredInput: "必填栏位，请重新输入",
    requiredCharacters: "必填栏位。请输入至少8个字元，并包含至少一个大写、一个小写、一个数字和一个特殊字元。",
    passwordAgain: "确认新密码",
    required: "必填栏位, 确认密码需与新密码相同",
    saveBtn: "送出",
    accountDelete: "帐号删除",
    confirmDelete: "您的帐号将被永久删除，您一旦删除后，帐号将无法复原，请您务必确定操作。",
    deleteAccount: "删除帐号",
};