<?php 
    $objectManager = \Magento\Framework\App\ObjectManager::getInstance();
    $customerSession = $objectManager->create('Magento\Customer\Model\Session');
    if($customerSession->isLoggedIn()) : ?>
        <script>
            console.log("login")
            window.hannstar = 
                { islogin:true,
                  userName:"<?php echo $customerSession->getCustomer()->getName();?>",
                  email:"<?php echo $customerSession->getCustomer()->getEmail();?>" 
                }
        </script>
<?php else: ?>
	<script>
        console.log("not login");
        window.hannstar = {islogin:false}
    </script>
<?php endif;?>