<?php
/*
product list 
left bar 
filter block
after filter
 */
?>

<?php if ($block->canShowBlock()) : ?>
    <div class="block filter">
        <div class="block-title filter-title">
            view.phtml
        </div>
        <div class="block-content filter-content">
          
            <?= $block->getChildHtml('state') ?>
            <?php if ($block->getLayer()->getState()->getFilters()) : ?>
                <div class="block-actions filter-actions">
                    <a href="<?= $block->escapeUrl($block->getClearUrl()) ?>" class="action clear filter-clear"><span><?= $block->escapeHtml(__('Clear All')) ?></span></a>
                </div>
            <?php endif; ?>
            
            <?php $wrapOptions = false; ?>
            
            <?php foreach ($block->getFilters() as $filter) : ?>

             
                <?php if (!$wrapOptions) :  ?>
                    <strong role="heading" aria-level="2" class="block-subtitle filter-subtitle">
                      <?/*選單名稱*/?>
                      <?= $block->escapeHtml(__('Shopping Options')) ?>
                    </strong>

                    <dl class="filter-options" id="narrow-by-list">
                    <?php $wrapOptions = true;
                      endif; ?>

                    <?php if ($filter->getItemsCount()) : ?>
                        <dt role="heading" aria-level="3" class="filter-options-title" style="color:#1979c3;">
                          
                          ==
                          <?= $block->escapeHtml(__($filter->getName())) ?>
                          ==
                        </dt>

                        <dd class="filter-options-content"><?= /* @noEscape */ $block->getChildBlock('renderer')->render($filter) ?></dd>


                    <?php endif; ?>
            <?php endforeach; ?>
            

            
            <?php if ($wrapOptions) : ?>
                </dl>
            <?php endif; ?>

        </div>
    </div>
<?php endif; ?>

