export const Account_Partner = {
    breadcrumbsLinkFrontPage: "Home Page",
    breadcrumbsLinkMemberCentre:"Member Center",
    breadcrumbsLinkMemberCentrePermissions:"My Permission",
    JobAttributes:{
        title: "Job Function",
        businessRelated:"Sales",
        purchasing:"Purchasing",
        related:"Research & Development",
        qualityRelated:"Quality",
        projectManagement :"Project Management",
        management :"Operation Management",
        other:"Others",
    },
    InterestedType:{
        title: "Interested Application (multiple choice)",
        smartRetail:"Smart Retailing",
        wisdomRecreation:"Smart Edutainment",
        intelligentBuilding:"Smart Building",
        healthCare:"Healthcare",
        transportation:"Transportation",
        smartManufacturing:"IIoT",
    },
    BusinessType: {
        title: "Business Type",
        option1: "Material Supplier",
        option2:"Equipment Supplier",
        option3:"Normal Supplier",
    },
    CompanyEmpNumber: {
        title: "Employee Number",
        option1: "<100",
        option2: "100-500", 
        option3: "500-1000", 
        option4: ">1000", 
      },
      AnnualRevenue: {
        title: "Currency of Annual Revenue(USD)",
        option1: "<1M",
        option2: "1M-5M", 
        option3: "5M-10M", 
        option4: "10M-30M",
        option5: ">30M",
      },
      CompanyStockOn: {
        title: "List Company",
        option1: "Yes",
        option2: "No",
    },
    CompanyMA1: {
        title: "Main sales categories of your company (multiple choice)",
        option1: "Smart Automotive",
        option2: "Wearable",
        option3: "Industrial Display",
        option4: "Smart Phone",
        option5: "Consumer Electronics",
        option6: "Others",
      },
    HannstarYN: {
        title: "If your company is HannStar supplier already?",
        option1: "Yes",
        option2: "No/Not sure",
      },
   JobTitle: {
        title: "Job Title",
        option1: "Founder", 
        option2: "CEO", 
        option3: "Manager", 
        option4: "Supervisor",
        option5: "Specialist",
        option6: "Engineer",
        option7: "Others",
      },
      ApplicableArea: {
        title: "Applicable Area",
        option1:"Array",
        option2:"Cell", 
        option3:"Color Filter",
        option4:"Touch", 
        option5:"Module", 
        option6:"Factory Service", 
      },
      TechnicalStaff: {
        title: "Technical Staff",
        option1:"<10", 
        option2:"10-30", 
        option3:"30-100",
        option4:">100", 
      },
      HannstarCode: "Please provide HannStar supplier code (6-digit)",
    CompanyMA2:"Company Sales Area-1",
    CompanyMA3:"Company Sales Area-2",
    CompanyMA4:"Company Sales Area-3",
    TOP1:"Main Customer-1",
    TOP2:"Main Customer-2",
    TOP3:"Main Customer-3",
    CompanyRemark: "Remark",
    TaxNo: "Tax ID Number",
    Weblink: "Company Website",
    Country: "Area",
    AreaCity: "City",
    AreaAddress: "Address",
    CompanyName: "Company Name",
    CompanySName: "Company Key Words",
    PhoneNumber0: "",
    PhoneNumber1: "Phone Number",
    PhoneNumber2: "Ext.",
    CellPhoneNumber0: "",
    CellPhoneNumber1: "Mobile Phone Number",
    ApplyMembership: "Enterprise Member Application Form",
    Step1: "Step 1. Please select your role",
    Step2: "Step 2. Applicator Information",
    Step3: "Step 3. Enterprise Information",
    Step4: "Step 4. To provide better service, please confirm if your company is HannStar supplier already?",
    Goback: "Return",
    Notes: "Remark",
    Application: "Submit",
    Required: "Required field. Please enter again."
};