export const Account_MyAccount = {
    breadcrumbsLinkFrontPage: "Home Page",
    breadcrumbsLinkMemberCentre:"Member Center",
    breadcrumbsLinkMemberCentreHref: "",
    breadcrumbsLinkAccountInfo: "Account Information",
    personal: "Personal Portal",
    account: "Account Information",
    personalInfo: "Personal Information",
    edit: "Edit",
    name: "Name",
    email: "email",
    subscription: "Subscription",
    companyInfo: "Company Information",
    companyName: "Company Name",
    business: "Business Type",
    applicable: "Applicable Area",
};