export const Account_Application = {
    breadcrumbsLinkFrontPage: "Home Page",
    breadcrumbsLinkMemberCentre:"Member Center",
    breadcrumbsLinkAuthManagement: "Permission Management",
    customerNormalIndustryAtricles:"Industry and application articles",
    customerNormalProductQuery: "Product search",
    customerNormalNewTechnology: "New technology collaboration",
    customerNormalOnlineChatRoom: "Chatbot",
    customerEnterpriseProductQuotation: "Featured product quotation includes components, solutions and final products",
    customerEnterpriseCustomizedService: "Customization service quotation regarding components, solutions and final products",
    customerEnterpriseRMAApply: "RMA Application",
    customerEnterpriseAnalyzeApply: "Analysis request",
    customerEnterpriseGreenRegulationApply: "Green Eco application",
    customerEnterpriseHSDCustomerService: "+ Everything in basic member",
    partnerNormalNewTechnology: "New technology collaboration",
    partnerNormalIndustryAtricles: "Industry and application articles",
    partnerNormalProductQuery: "Product search",
    partnerNormalOnlineChatRoom: "Chatbot",
    partnerEnterpriseSupplierPlatform: "Supplier exchange platform",
    partnerEnterpriseHSDSupplierService: "+ Everything in basic member",
    contentTitle: "Permission Application",
    contentSubTitle: "Permission Types",
    contentRank: "Benefits",
    contentText: "You are now",
    contentMember: "Basic Member",
    contentPendingText: "Your current status",
    contentPendingStates: "Enterprise member application - under review",
    contentBecome: "You can further become",
    contentCompanyMember: "Enterprise Member",
    contentCustomerPermission: "Customer Benefits",
    contentApplyMembership: "Apply for Customer Enterprise Member",
    contentApplyPartnership: "Apply for Supplier Enterprise Member",
    contentSupplierLimit: "Supplier Benefits",
};