export const MFAQRCODE = {
    pageTitle: "Two-Factor Authentication (2FA)",
    subTitle: "Providing more powerful protection to your account password, please help complete Two-Factor Authenticator.",
    noteTitle:
      "You need to enter a 6-digit code to access your account while logging in, which is automatically generated by your authenticator appe very 30 seconds.",
    formTitle: "Three Steps to Bind Two-Factor Authentication",
    installText1: "Install Authenticator App",
    installText2: "on your Mobile Device",
    bind: "Identity Binding",
    verifylText1: "Please Enter a Code",
    verifylText2: "from your Authenticator App",
    bindSubTitle:
      "Scan the QR code or enter a secret key to bind identity with your authenticator app.",
    bindNote: "show secret key",
    verifyBtn: "Complete 2FA ",
    errorMessage: "Required field. Wrong format, please enter again.",
    placeholder: "Please enter a code",
  };