<h1>document360</h1>
<script>
    console.log("document360");
    fetch('https://ef9ziroflf.execute-api.us-west-2.amazonaws.com/eipTest', {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json;charset=UTF-8',
      'X-API-Key': '7zSxaQEJKXhlX0lqPePREonXGuHHS31Lv5wRkFf0',
    },
    body: JSON.stringify({
   "functionName":"Magento",
   "method":"GetAllArticles",
   "language":"zh-hant",
   "keyValue":"hannstar/service/technical support/education"           
})
  }).then(response => response.json())
</script>